[".config/nvim"]
type = "git-repo"
url = "https://github.com/dragoscirjan/nvim-config.git"
refreshPeriod = "168h"                                  # Updates weekly

["AppData/Local/nvim"]
type = "git-repo"
url = "https://github.com/dragoscirjan/nvim-config.git"
refreshPeriod = "168h"                                  # Updates weekly

[".config/opencode"]
type = "git-repo"
url = "https://github.com/dragoscirjan/opencode-config.git"
refreshPeriod = "168h"                                      # Updates weekly

[".pi"]
type = "git-repo"
url = "https://github.com/dragoscirjan/pi-config.git"
refreshPeriod = "168h"                                      # Updates weekly



